# Openfoam Job parameters
userName: hpcuser
userId: 10000
groupName: hpcuser
groupId: 10000
procsPerNode: 96
procsTotal: 192
numberOfNodes: 2
acrName: acrurhlmto7ozbkk
blobStorageAccountName: to_be_defined_on_command_line
sasToken: to_be_defined_on_command_line 