apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  protocol: nfs
  skuName: Premium_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homedir
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-csi-nfs
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: mpi-pod1
spec:
  containers:
  - name: hpcx-test
    #image: __ACRNAME__.azurecr.io/ubuntu2004-mofed-hpcx:latest
    image: acrrk344f42c74vy.azurecr.io/ubuntu2004-mofed-hpcx:latest
    securityContext:
      capabilities:
        add: ["IPC_LOCK"]
      privileged: true
    resources:
      requests:
        mellanox.com/shared_hca_rdma: 1
      limits:
        mellanox.com/shared_hca_rdma: 1
    command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: "/home"
      name: homedir
  volumes:
  - name: homedir
    persistentVolumeClaim:
      claimName: homedir
---
apiVersion: v1
kind: Pod
metadata:
  name: mpi-pod2
spec:
  containers:
  - name: hpcx-test
    #image: __ACRNAME__.azurecr.io/ubuntu2004-mofed-hpcx:latest
    image: acrrk344f42c74vy.azurecr.io/ubuntu2004-mofed-hpcx:latest
    securityContext:
      capabilities:
        add: ["IPC_LOCK"]
      privileged: true
    resources:
      requests:
        mellanox.com/shared_hca_rdma: 1
      limits:
        mellanox.com/shared_hca_rdma: 1
    command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: "/home"
      name: homedir
  volumes:
  - name: homedir
    persistentVolumeClaim:
      claimName: homedir
