# Application image
FROM __ACRNAME__.azurecr.io/ubuntu2004-mofed-hpcx:latest

WORKDIR /root

# Install OpenFoam dependencies
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" TZ="Europe/London" \
        apt-get -o apt::install-recommends=false install -y gnome-panel \
		   gnome-flashback \ 
		   gnome-session-flashback \ 
		   indicator-applet-appmenu \
            	   software-properties-common

# Install OpenFoam v10
RUN sh -c "wget -O - https://dl.openfoam.org/gpg.key > /etc/apt/trusted.gpg.d/openfoam.asc"
RUN add-apt-repository http://dl.openfoam.org/ubuntu
RUN sudo apt-get update; sudo apt-get -y install openfoam10

## Setup user
# ENV USERNAME hpcuser
# ENV HOME /home/${USERNAME}
# ENV SSHDIR ${HOME}/.ssh

# RUN ls -al /home
# RUN addgroup ${USERNAME}
# RUN adduser --disabled-password --ingroup ${USERNAME} --home /home/${USERNAME} --gecos "" ${USERNAME}
# RUN echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Passwordless ssh connection between containers.
# RUN mkdir -p ${SSHDIR}
# RUN ssh-keygen -t rsa -N "" -f ${SSHDIR}/id_rsa
# RUN cat ${SSHDIR}/id_rsa.pub >> ${SSHDIR}/authorized_keys && chmod 600 ${SSHDIR}/authorized_keys
# RUN echo "Host *\n\tStrictHostKeyChecking no" >> /home/${USERNAME}/.ssh/config && chmod 600 /home/${USERNAME}/.ssh/config

# RUN chown -R ${USERNAME}:${USERNAME} ${SSHDIR}

## ssh server
RUN mkdir /var/run/sshd
EXPOSE 22
#CMD ["/usr/sbin/sshd", "-D"]

COPY entrypoint.sh /entrypoint.sh 
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

